# Site settings

title: Practice Workshop on MATIN/PyMKS
header-img: img/home-bg.jpg
email: ahafeez@gatech.edu
description: "Workshop on MATIN and PyMKS"
baseurl: "/project-pages"
url: "http://matin-hub.github.io"
github_username:  matin-hub
project_repository: MATIN-PyMKS Workshop

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
