# Site settings

title: Practice Workshop on MATIN
header-img: img/home-bg.jpg
email: ahafeez@gatech.edu
description: "Covers Project pages (tool for collaboration), tutorial on PyMKS, Homogenization and Localization"
baseurl: "/matin-workshop"
url: "http://ahafeez7.github.io"
github_username:  ahafeez7
project_repository: MATIN-PyMKS Workshop

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
